---
name: build-container

env:
  GH_TOKEN: ${{ github.token }}
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on: workflow_call

jobs:
  build-container:
    runs-on: ubuntu-22.04
    outputs:
      json: ${{ steps.metadata.outputs.json }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: extract metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=ref,event=pr
            type=ref,event=branch

      - name: build container
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          labels: ${{ steps.metadata.outputs.labels }}
          tags: ${{ steps.metadata.outputs.tags }}

      - name: debug
        run: echo "${{ fromJSON(steps.metadata.outputs.json).tags[0] }}"

  build-willow:
    uses: ./.github/workflows/build-willow.yml
    needs: build-container
    with:
      container-image: ${{ fromJSON(needs.build-container.outputs.json).tags[0] }}
