---
name: clang-format
on:
  - pull_request
jobs:
  clang-format:
    name: clang-format
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: clang-format
        uses: jidicula/clang-format-action@v4.11.0
        with:
          clang-format-version: 15
          check-path: 'main'
